name: Coverage

on:
  pull_request:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - uses: actions/checkout@v2

      - uses: artiomtr/jest-coverage-report-action@v2.0-rc.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          threshold: 60
